# Generated by Django 5.2.7 on 2025-10-09 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_college_adminhod_college_course_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='student_management_app.college'),
        ),
        migrations.AddField(
            model_name='sessionyear',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_management_app.college'),
        ),
    ]
