# Generated by Django 5.2.7 on 2025-10-09 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_customuser_college_sessionyear_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_management_app.college'),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_management_app.college'),
        ),
    ]
