# Generated by Django 5.2.7 on 2025-10-09 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_attendance_college_attendancereport_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_management_app.college'),
        ),
    ]
