# Generated by Django 5.2.7 on 2025-10-09 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_studentresult_college'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollegeProfile',
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='adminhod',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='student_management_app.college'),
        ),
        migrations.AddField(
            model_name='semester',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='student_management_app.college'),
        ),
        migrations.AddField(
            model_name='staffs',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='staff_profile/'),
        ),
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='adminhod',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hod_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adminhod',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hods', to='student_management_app.college'),
        ),
        migrations.AlterField(
            model_name='adminhod',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hods', to='student_management_app.department'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='student_management_app.college'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='student_management_app.course'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='session_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='student_management_app.sessionyear'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='student_management_app.attendance'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_reports', to='student_management_app.college'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to='student_management_app.students'),
        ),
        migrations.AlterField(
            model_name='course',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='student_management_app.college'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='feedbackstaff',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='student_management_app.staffs'),
        ),
        migrations.AlterField(
            model_name='feedbackstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='student_management_app.students'),
        ),
        migrations.AlterField(
            model_name='leavereportstaff',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='student_management_app.staffs'),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='student_management_app.students'),
        ),
        migrations.AlterField(
            model_name='sessionyear',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_years', to='student_management_app.college'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='student_management_app.college'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='student_management_app.department'),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='student_management_app.college'),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='student_management_app.students'),
        ),
        migrations.AlterField(
            model_name='students',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='students',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='student_management_app.college'),
        ),
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='student_management_app.course'),
        ),
        migrations.AlterField(
            model_name='students',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='student_management_app.department'),
        ),
        migrations.AlterField(
            model_name='students',
            name='session_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='student_management_app.sessionyear'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('course', 'session_year', 'attendance_date', 'college')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('college', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('college', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('college', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionyear',
            unique_together={('college', 'session_start_year', 'session_end_year')},
        ),
    ]
